### ISSUE TITLE
Noarch repodata.json is empty for proxy channels

### ISSUE THREAD

**Issue by janjagusch** [mamba-org/quetz#527]
In our quetz server, we proxy `conda-forge` into a channel of the same name:

```
  {
    "name": "conda-forge",
    "description": null,
    "private": true,
    "size_limit": null,
    "ttl": 36000,
    "mirror_channel_url": "https://conda.anaconda.org/conda-forge",
    "mirror_mode": "proxy",
    "members_count": 1,
    "packages_count": 0
  },
```

Installation often fails because certain packages cannot be found. We narrowed the issue down to the noarch `repodata.json` being empty. Navigating to `/get/conda-forge/noarch/repodata.json` yields:

```
{
  "info": {
    "subdir": "noarch"
  },
  "packages": {},
  "packages.conda": {},
  "repodata_version": 1
}
```

This problem only occurs for the noarch platform. Also, in our package backend (GCS) we have a cached version of the `repodata.json`, which is not empty (it's 55MB large).

Any idea what might be causing this?

**Comment by wolfv** [comment]
hmmm, this is the code in question: https://github.com/mamba-org/quetz/blob/05dbfc65529c6a81acdab899ad509d85496802cd/quetz/main.py#L1645-L1654

I wonder if the gzip magic does something bad here: https://github.com/mamba-org/quetz/blob/05dbfc65529c6a81acdab899ad509d85496802cd/quetz/main.py#L1673-L1683

Since we might not have the proper `repodata.json.gz` file on the package store ...

**Comment by janjagusch** [comment]
> hmmm, this is the code in question:
> 
> https://github.com/mamba-org/quetz/blob/05dbfc65529c6a81acdab899ad509d85496802cd/quetz/main.py#L1645-L1654
> 
> I wonder if the gzip magic does something bad here:
> 
> https://github.com/mamba-org/quetz/blob/05dbfc65529c6a81acdab899ad509d85496802cd/quetz/main.py#L1673-L1683
> 
> Since we might not have the proper `repodata.json.gz` file on the package store ...

I just checked the `repodata.json.gz` and it's empty (check file size):

![image](https://user-images.githubusercontent.com/25852654/167653031-49f4e6e1-73eb-43a8-9531-d9f75b25ffcc.png)

Interestingly, the other platform don't contain the `repodata.json.gz`, only `repodata.json`.

**Comment by janjagusch** [comment]
> > https://conda.anaconda.org/conda-forge
> 
> One more thing: `repodata.json.gz` also doesn't seem to exist on the upstream channel, see: https://conda.anaconda.org/conda-forge/noarch/repodata.json.gz
> 
> ![image](https://user-images.githubusercontent.com/25852654/167654458-6c6aa684-9d47-4f87-99be-043325cc2b7f.png)

Deleting `repodata.json.bz2` and `repodata.json.gz` seems to solve the issue for me. The question remains where these files come from, though.

**Comment by wolfv** [comment]
OK, so the bug goes as follows:

- we added a repodata.json.gz file to support returning / streaming gzip compressed files from S3 buckets and similar
- we do initialize every channel with an empty noarch repodata.json because the existence of teh `noarch/repodata.json` is what marks a channel as "existing"
- apparently we do initialize even a proxy-mirror channel with the static `noarch/repodata.json` files (including the `.gz` / `.bz2` ones). We should not do that.
- the `repodata.json.gz` is a quetz-specific extension (and a bit of a workaround for OVH because they don't properly support setting the `Content-Encoding` header for a given file)

**Comment by wolfv** [comment]
This is where we call `update_indexes` for all kinds of channels: https://github.com/mamba-org/quetz/blob/59adbfdda13f75218d89b1c8c20ac090408311d4/quetz/main.py#L725

That creates the empty `noarch/repodata.json` ...

Should we just not call that for a proxy-mirror channel?

**Comment by janjagusch** [comment]
> This is where we call `update_indexes` for all kinds of channels:
> 
> https://github.com/mamba-org/quetz/blob/59adbfdda13f75218d89b1c8c20ac090408311d4/quetz/main.py#L725
> 
> That creates the empty `noarch/repodata.json` ...
> 
> Should we just not call that for a proxy-mirror channel?

Sounds reasonable to me. 👍

**Comment by wolfv** [comment]
On the other hand, a better solutoin might be to create the `.gz` files so that we can serve gzipped repodata (which saves a lot, it's 20% or so of the full repodata). E.g. instead of downloading 120Mb, you only need 20 or so.
Did you experience long downloads or are you gzipping the responses through nginx?

**Comment by janjagusch** [comment]
> On the other hand, a better solutoin might be to create the `.gz` files so that we can serve gzipped repodata (which saves a lot, it's 20% or so of the full repodata). E.g. instead of downloading 120Mb, you only need 20 or so. Did you experience long downloads or are you gzipping the responses through nginx?

So far I don't think long download times have been an issue for us. But if we could build it in a way such that we have to send a lot less data over the network, then i would be all in favour for that.

**Comment by wolfv** [comment]
quetz is released, with this bug fixed.

**Comment by janjagusch** [comment]
thank you!
